/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hmis;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class lab extends javax.swing.JFrame {

    /**
     * Creates new form lab
     */
    public lab() {
        initComponents();
        showData();
        currentDate();
        this.setLocationRelativeTo(null);
    }
    
    public void showData(){
        try{
            Class.forName("org.postgresql.Driver");
            java.sql.Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","postgres","kanyingi254");
            Statement st = conn.createStatement();
            String query = "SELECT * FROM public.lab_request";
            ResultSet rs = st.executeQuery(query);
            register_report.setModel(DbUtils.resultSetToTableModel(rs));
            conn.close();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    public void currentDate() {
    Calendar cal = new GregorianCalendar();
    int month = cal.get(Calendar.MONTH) + 1;
    int year = cal.get(Calendar.YEAR);
    int day = cal.get(Calendar.DAY_OF_MONTH);

    date_txt.setText(day+ "/" + month + "/" + year);

    int second = cal.get(Calendar.SECOND);
    int minute = cal.get(Calendar.MINUTE);
    int hour = cal.get(Calendar.HOUR_OF_DAY);

    time_txt.setText(hour + "." + minute + "." + second);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        register_report = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        test_requested = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        report_result = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        verified_by = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        pat_name_txt = new javax.swing.JTextField();
        pat_no_txt = new javax.swing.JTextField();
        date_txt = new javax.swing.JLabel();
        time_txt = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        persona_txt = new javax.swing.JLabel();
        db_connection_status = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        register_report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient No", "Patient Name", "Test", "Bench", "Date", "Time"
            }
        ));
        register_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_reportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(register_report);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jTabbedPane1.addTab("Occupancy", jPanel1);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Lab Test Requested"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        test_requested.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Test Requested", "Category", "Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        test_requested.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                test_requestedMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(test_requested);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jPanel5, gridBagConstraints);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporting Lab Results"));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        report_result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Test", "Code", "Parameter", "Result", "Lower Limit", "Upper Limit", "Units"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(report_result);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel7.add(jScrollPane3, gridBagConstraints);

        jLabel1.setText("Results Verified By");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel7.add(jLabel1, gridBagConstraints);

        verified_by.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Susan Wambugu" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel7.add(verified_by, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jPanel7, gridBagConstraints);

        jPanel8.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel8.add(jButton1, gridBagConstraints);

        jButton2.setText("CLEAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel8.add(jButton2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jPanel8, gridBagConstraints);

        jTabbedPane1.addTab("Reporting lab Results", jPanel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jButton3.setText("Patient Card");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(jButton3, gridBagConstraints);

        pat_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pat_name_txtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(pat_name_txt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(pat_no_txt, gridBagConstraints);

        date_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Date"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(date_txt, gridBagConstraints);

        time_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Time"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(time_txt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jPanel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        jPanel3.add(jDateChooser2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel11.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel11.add(persona_txt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel11.add(db_connection_status, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel11, gridBagConstraints);

        jMenu6.setText("Setup");

        jMenu7.setText("Staff Registry");

        jMenuItem8.setText("Add User");
        jMenu7.add(jMenuItem8);

        jMenuItem9.setText("Edit User");
        jMenu7.add(jMenuItem9);

        jMenu6.add(jMenu7);

        jMenu8.setText("Operating Parameters");

        jMenuItem7.setText("Pharmacy");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenuItem10.setText("Laboratory");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        jMenu6.add(jMenu8);

        jMenu10.setText("Exit");
        jMenu6.add(jMenu10);

        jMenuBar1.add(jMenu6);

        jMenu1.setText("Registration");

        jMenuItem2.setText("Out Patient Registration");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Nursing");

        jMenuItem1.setText("Nursing Center");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Clinical");

        jMenuItem3.setText("Clerking");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Eye");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laboratory");

        jMenuItem6.setText("Laboratory LIMS");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu9.setText("Billing");

        jMenuItem11.setText("Cash Sale POS");
        jMenu9.add(jMenuItem11);

        jMenuBar1.add(jMenu9);

        jMenu5.setText("Reports");

        jMenuItem5.setText("Patient Card");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Clerking rgf = new Clerking();
        rgf.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Nursing().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Clerking().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void register_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_reportMouseClicked
        // TODO add your handling code here:
       DefaultTableModel model =(DefaultTableModel) register_report.getModel();
    int i = register_report.getSelectedRow();
    try{
        pat_no_txt.setText(model.getValueAt(i, 0).toString());
        pat_name_txt.setText(model.getValueAt(i, 1).toString());
    }catch(Exception e){
    }
    
    // Get the data from the selected row
    String column2Data = model.getValueAt(i, 2) != null ? model.getValueAt(i, 2).toString() : "";
    String column3Data = model.getValueAt(i, 3) != null ? model.getValueAt(i, 3).toString() : "";
    String column6Data = model.getValueAt(i, 6) != null ? model.getValueAt(i, 6).toString() : "";

    // Add a new tab to the JTabbedPane
    JPanel selectedPanel = jPanel4; // replace jPanel4 with the actual name of your JTabbedPane
    selectedPanel.setVisible(true);
    jTabbedPane1.setSelectedComponent(selectedPanel);

    // Set the data in the test_requested table
DefaultTableModel testRequestedModel = (DefaultTableModel) test_requested.getModel();
testRequestedModel.insertRow(0, new Object[]{column2Data, column3Data, column6Data});


    }//GEN-LAST:event_register_reportMouseClicked

    private void pat_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_name_txtActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        dispose();
        new lab().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          String path = "";
JFileChooser j = new JFileChooser();
j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
int x = j.showOpenDialog(this);

if (x == JFileChooser.APPROVE_OPTION) {
    path = j.getSelectedFile().getPath();
}

int rowIndex = register_report.getSelectedRow();

if (rowIndex != -1) {
    String Number = register_report.getValueAt(rowIndex, 0).toString();
    String Name = register_report.getValueAt(rowIndex, 1).toString();
    String Urgency = register_report.getValueAt(rowIndex, 2).toString();
    String Age = register_report.getValueAt(rowIndex, 3).toString();
    String Clinic = register_report.getValueAt(rowIndex, 4).toString();
    String Time = register_report.getValueAt(rowIndex, 5).toString();
    String Date = register_report.getValueAt(rowIndex, 6).toString();

    Document doc = new Document();

    try {
        // Save the PDF file with the patient number as the file name
        PdfWriter.getInstance(doc, new FileOutputStream(path + File.separator + Number + ".pdf"));

        // Add header with logo and text
        Paragraph header = new Paragraph();
        // Add logo
        Image logo = Image.getInstance("src\\main\\java\\com\\mycompany\\icons\\logo.png");
        logo.scaleAbsolute(100f, 100f);
        logo.setAlignment(Element.ALIGN_CENTER);
        header.add(logo);

        // Add header text
        Paragraph headerText = new Paragraph();
        headerText.add(new Phrase("BUNGOMA WEMA CENTER\n Fashion Place Plaza 2nd Floor, Hospital Road\n Opposite Shariffs Centre Next to County Comfort Hotel\n P.o Box 2270-50200 Bungoma \n Tel: 0726982221 \n Email: wemacentre@gmail.com \n"));
        headerText.setAlignment(Element.ALIGN_CENTER);
        header.add(headerText);

        // Center the header
        header.setAlignment(Element.ALIGN_CENTER);

        // Add header to the document
        doc.open();
        doc.add(header);
        doc.add(new Paragraph("\n")); // Add a blank paragraph



        // Add patient data table
        PdfPTable report = new PdfPTable(new float[] { 1, 2 }); // 2 columns: labels on left, data on right
        report.setWidthPercentage(100f);

        report.addCell("Patient Number");
        report.addCell(Number);
        report.addCell("Patient Name");
        report.addCell(Name);
        report.addCell("Gender");
        report.addCell(Urgency);
        report.addCell("Age");
        report.addCell(Age);
        report.addCell("ID");
        report.addCell(Clinic);
        report.addCell("Residence");
        report.addCell(Time);
        report.addCell("Clinic");
        report.addCell(Date);

        doc.add(report);
        
        // Add a row with the text "VITAL SIGNS"


PdfPTable vitalSignsRow = new PdfPTable(1);
Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
Phrase vitalSignsPhrase = new Phrase("VITAL SIGNS", boldFont);
vitalSignsRow.addCell(vitalSignsPhrase);
vitalSignsRow.setWidthPercentage(100f);
doc.add(vitalSignsRow);



      
        
        

// Add vital signs data table
PdfPTable vitalSignsTable = new PdfPTable(new float[] { 1, 1, 5 }); // 3 columns: date, time, vital signs
vitalSignsTable.setWidthPercentage(100f);

// Retrieve vital signs data for the selected patient number
String patNumber = pat_no_txt.getText();
String query = "SELECT  height, weight, bmi, systolic, diastolic, temperature, pressure, oxygen_saturation, date, time FROM vitals  WHERE pat_no = ? order by date ASC, time DESC " ;
try {
    Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","postgres","kanyingi254");
    PreparedStatement pst = conn.prepareStatement(query);
    pst.setString(1, patNumber);
    ResultSet rs = pst.executeQuery();

    // Add the vital signs data to the table
    while (rs.next()) {
        String height = rs.getString("height");
        String weight = rs.getString("weight");
        String bmi = rs.getString("bmi");
        String systolic = rs.getString("systolic");
        String diastolic = rs.getString("diastolic");
        String temperature = rs.getString("temperature");
        String pressure = rs.getString("pressure");
        String oxygenSat = rs.getString("oxygen_saturation");
        String date = rs.getString("date");
        String time = rs.getString("time");

        String vitalSigns = "Height: " + height + ", Weight: " + weight + ", BMI: " + bmi + ", Systolic: " + systolic + ", Diastolic: " + diastolic + ", Temperature: " + temperature + ", Pressure: " + pressure + ", Oxygen Saturation: " + oxygenSat;

        vitalSignsTable.addCell(date);
        vitalSignsTable.addCell(time);
        vitalSignsTable.addCell(vitalSigns);
    }

    // Add the vital signs table to the document
    doc.add(vitalSignsTable);
    
    // Add a row with the text "VITAL SIGNS"
PdfPTable doctorsNotesLabel = new PdfPTable(1);
Font bold = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
Phrase phrase = new Phrase("DOCTORS NOTES", bold);
doctorsNotesLabel.addCell(phrase);
doctorsNotesLabel.setWidthPercentage(100f);
doc.add(doctorsNotesLabel);

    
// Add doctors notes data table
PdfPTable doctorsNotesTable = new PdfPTable(new float[] { 1, 1, 4 }); // 3 columns: date, time, note
doctorsNotesTable.setWidthPercentage(100f);

// Retrieve doctors notes data for the selected patient number
String doctorsNotesQuery = "SELECT history, diagnosis, treatment, date, time FROM public.doc_notes WHERE pat_no = ? ORDER BY date ASC, time DESC";
PreparedStatement doctorsNotesPst = conn.prepareStatement(doctorsNotesQuery);
doctorsNotesPst.setString(1, patNumber);
ResultSet doctorsNotesRs = doctorsNotesPst.executeQuery();

// Add the doctors notes data to the table
while (doctorsNotesRs.next()) {
    String history = doctorsNotesRs.getString("history");
    String diagnosis = doctorsNotesRs.getString("diagnosis");
    String treatment = doctorsNotesRs.getString("treatment");
    String date = doctorsNotesRs.getString("date");
    String time = doctorsNotesRs.getString("time");

    String note = "History: " + history + "\nDiagnosis: " + diagnosis + "\nTreatment: " + treatment;
    doctorsNotesTable.addCell(date);
    doctorsNotesTable.addCell(time);
    doctorsNotesTable.addCell(note);
}

// Add the doctors notes table to the document
doc.add(doctorsNotesTable);

    // Add a row with the text "VITAL SIGNS"
PdfPTable investigationslabel = new PdfPTable(1);
//Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
Phrase phraseinv = new Phrase("INVESTIGATION", boldFont);
investigationslabel.addCell(phraseinv);
investigationslabel.setWidthPercentage(100f);
doc.add(investigationslabel);

    
// Add doctors notes data table
PdfPTable investigations = new PdfPTable(new float[] { 1, 1, 4 }); // 3 columns: date, time, note
investigations.setWidthPercentage(100f);

// Retrieve doctors notes data for the selected patient number
String investigationsQuery = "SELECT  test_requested, date, time FROM public.lab_request WHERE patient_no = ? ORDER BY date ASC, time DESC";
PreparedStatement investigationsPst = conn.prepareStatement(investigationsQuery);
investigationsPst.setString(1, patNumber);
ResultSet investigationsRs = investigationsPst.executeQuery();

// Add the doctors notes data to the table
while (investigationsRs.next()) {
    String test = investigationsRs.getString("test_requested");
    String date = investigationsRs.getString("date");
    String time = investigationsRs.getString("time");

    String note = "Investigation: " + test;
    investigations.addCell(date);
    investigations.addCell(time);
    investigations.addCell(note);
}

// Add the doctors notes table to the document
doc.add(investigations);

// Add a row with the text "LABORATORY RESULTS"
PdfPTable labResultsLabel = new PdfPTable(1);
//Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
Phrase phraseLabResults = new Phrase("LABORATORY RESULTS", boldFont);
labResultsLabel.addCell(phraseLabResults);
labResultsLabel.setWidthPercentage(100f);
doc.add(labResultsLabel);

// Add laboratory results data table
PdfPTable labResultsTable = new PdfPTable(new float[] { 1, 1, 1, 1, 1 }); // 5 columns: parameter, result, lower limit, upper limit, status
labResultsTable.setWidthPercentage(100f);



// Retrieve laboratory results data for the selected patient number
String labResultsQuery = "SELECT test, parameter, result, lower, upper, unit, verified, date, time FROM public.lab_results WHERE patient_no = ? ORDER BY date ASC, time DESC";
PreparedStatement labResultsPst = conn.prepareStatement(labResultsQuery);
labResultsPst.setString(1, patNumber);
ResultSet labResultsRs = labResultsPst.executeQuery();

// Initialize variables to track the current test
String currentTest = "";
boolean isFirstRow = true;

// Declare the verified variable
String verified = "";

// Add the laboratory results data to the table
while (labResultsRs.next()) {
    String test = labResultsRs.getString("test");
    String parameter = labResultsRs.getString("parameter");
    String labResult = labResultsRs.getString("result");
    String lower = labResultsRs.getString("lower");
    String upper = labResultsRs.getString("upper");
    String unit = labResultsRs.getString("unit");
    String date = labResultsRs.getString("date");
    String time = labResultsRs.getString("time");

    // If the test changes, add a new row with the test name in bold
    if (!test.equals(currentTest)) {
        if (!isFirstRow) {
            labResultsTable.completeRow(); // Complete the previous row
        }

        // Add a row with the test name
        PdfPCell testCell = new PdfPCell();
        testCell.setColspan(5);
        Phrase testPhrase = new Phrase("PROCEDURE: " + test, boldFont);
        testCell.addElement(testPhrase);
        labResultsTable.addCell(testCell);
        
        // Add headers for the columns
        labResultsTable.addCell(new PdfPCell(new Phrase("Parameter", boldFont)));
        labResultsTable.addCell(new PdfPCell(new Phrase("Result", boldFont)));
        labResultsTable.addCell(new PdfPCell(new Phrase("Lower Limit", boldFont)));
        labResultsTable.addCell(new PdfPCell(new Phrase("Upper Limit", boldFont)));
        labResultsTable.addCell(new PdfPCell(new Phrase("Status", boldFont)));

        currentTest = test;
        isFirstRow = false;
    }

    // Merge the unit with the result and add it to the table
    String resultWithUnit = labResult + " " + unit;
    labResultsTable.addCell(parameter);
    labResultsTable.addCell(resultWithUnit);
    labResultsTable.addCell(lower);
    labResultsTable.addCell(upper);

    // Check if the result is within the limits
    boolean isWithinLimits = (Double.parseDouble(labResult) >= Double.parseDouble(lower) && Double.parseDouble(labResult) <= Double.parseDouble(upper));

    // Set the status cell color based on the result's position relative to the limits
    PdfPCell statusCell = new PdfPCell();
    statusCell.setBackgroundColor(isWithinLimits ? BaseColor.GREEN : BaseColor.RED);
    labResultsTable.addCell(statusCell);
    
    // Retrieve the "verified" value
    verified = labResultsRs.getString("verified");
}

// Complete the last row if there are any remaining cells
if (!isFirstRow) {
    labResultsTable.completeRow();
}

// Add the laboratory results table to the document
doc.add(labResultsTable);


// Add a row with the text "Results Verified By"
PdfPTable verifiedByRow = new PdfPTable(1);
Phrase verifiedByPhrase = new Phrase();
Chunk verifiedByChunk = new Chunk("Results Verified By: ", boldFont);
verifiedByChunk.append(verified);
verifiedByPhrase.add(verifiedByChunk);
verifiedByRow.addCell(verifiedByPhrase);
verifiedByRow.setWidthPercentage(100f);
doc.add(verifiedByRow);


    // Add a row with the text "VITAL SIGNS"
PdfPTable drugslabel = new PdfPTable(1);
//Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
Phrase drugsinv = new Phrase("DRUGS REQUESTED", boldFont);
drugslabel.addCell(drugsinv);
drugslabel.setWidthPercentage(100f);
doc.add(drugslabel);

    
// Add doctors notes data table
PdfPTable drugs = new PdfPTable(new float[] { 1, 1, 4 }); // 3 columns: date, time, note
drugs.setWidthPercentage(100f); // Set the table width to 100%

// Retrieve doctors notes data for the selected patient number
String drugsQuery = "SELECT drug,  quantity_requested, strength, date, time, notes FROM public.drugs_requested WHERE pat_no = ? ORDER BY date ASC, time DESC";
PreparedStatement drugsPst = conn.prepareStatement(drugsQuery);
drugsPst.setString(1, patNumber);
ResultSet drugsRs = drugsPst.executeQuery();

// Add the doctors notes data to the table
while (drugsRs.next()) {
    String test = drugsRs.getString("drug");
    String date = drugsRs.getString("date");
    String time = drugsRs.getString("time");

    String note = "Drug: " + test;
    drugs.addCell(date);
    drugs.addCell(time);
    drugs.addCell(note);
}

// Set the number of columns to span for the note column
int noteColumnSpan = 3;
drugs.getDefaultCell().setColspan(noteColumnSpan);

// Add the doctors notes table to the document
doc.add(drugs);







// Close the database connection
conn.close();



    // Close the document
    doc.close();
    
} catch (SQLException ex) {
    Logger.getLogger(Clerking.class.getName()).log(Level.SEVERE, null, ex);
}

 



        
        
        
        JOptionPane.showMessageDialog(null, "File Downloaded Successfully", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);

    } catch (FileNotFoundException ex) {
        Logger.getLogger(Clerking.class.getName()).log(Level.SEVERE, null, ex);
    } catch (DocumentException ex) {
        Logger.getLogger(Clerking.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(Clerking.class.getName()).log(Level.SEVERE, null, ex);
    }

    doc.close();
}




    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        dispose();
        new parameter_lab().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Register_pharms().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void test_requestedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test_requestedMouseClicked
        // TODO add your handling code here:
  // Get the selected row index of test_requested table
    int rowIndex = test_requested.getSelectedRow();
    
    // Get the value of the 3rd column from the selected row in test_requested
    String selectedTest = (String) test_requested.getValueAt(rowIndex, 2);
 
    
    try {
        // Create a database connection
        Class.forName("org.postgresql.Driver");
        java.sql.Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","postgres","kanyingi254");
        
        // Execute the select query to retrieve data from the lab_parameters table
        PreparedStatement stmt = conn.prepareStatement("SELECT test, code, parameter, lower_limit, upper_limit, unit FROM public.lab_parameters WHERE code = ?");
        stmt.setString(1, selectedTest);
        ResultSet rs = stmt.executeQuery();

        
        // Check if the DefaultTableModel is set up correctly
        String[] columnNames = {"Code", "Test", "Parameter", "Result", "Lower Limit", "Upper Limit", "Unit"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        report_result.setModel(model);

        
        // Populate the report_result table with the retrieved data
        while (rs.next()) {
            String code = rs.getString("code");
            String test = rs.getString("test");
            String parameter = rs.getString("parameter");
            String lowerLimit = rs.getString("lower_limit");
            String upperLimit = rs.getString("upper_limit");
            String unit = rs.getString("unit");
            
            model.addRow(new Object[]{code, test, parameter, "", lowerLimit, upperLimit, unit});
            
            System.out.println(code + ", " + test + ", " + parameter + ", " + lowerLimit + ", " + upperLimit + ", " + unit);
        }
     
        
        // Close the database resources
        rs.close();
        stmt.close();
        conn.close();
       
    } catch (SQLException ex) {
        ex.printStackTrace();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(lab.class.getName()).log(Level.SEVERE, null, ex);
    }
                                             

    }//GEN-LAST:event_test_requestedMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // TODO add your handling code here:
    try {
    // Retrieve the data from the JTable
    DefaultTableModel model = (DefaultTableModel) report_result.getModel();
    int rowCount = model.getRowCount();
    String verify = verified_by.getSelectedItem().toString();
    String pat_no = pat_no_txt.getText();
    String pat_name = pat_name_txt.getText();
    String date = date_txt.getText();
    String time = time_txt.getText();

    // Establish a connection to the PostgreSQL database
    Class.forName("org.postgresql.Driver");
    java.sql.Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","postgres","kanyingi254");
    
    // Prepare the SQL statement
    String sql = "INSERT INTO public.lab_results (patient_no, patient_name, code, test, parameter, result, lower, upper, unit, verified, date, time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
    PreparedStatement pstmt = conn.prepareStatement(sql);
    
    // Loop through each row in the JTable and insert data into the database
    for (int i = 0; i < rowCount; i++) {
        // Retrieve values from the JTable and check for null
        String col1Value = model.getValueAt(i, 0) != null ? model.getValueAt(i, 0).toString() : "";
        String col2Value = model.getColumnCount() > 1 && model.getValueAt(i, 1) != null ? model.getValueAt(i, 1).toString() : "";
        String col3Value = model.getColumnCount() > 2 && model.getValueAt(i, 2) != null ? model.getValueAt(i, 2).toString() : "";
        String col4Value = model.getColumnCount() > 3 && model.getValueAt(i, 3) != null ? model.getValueAt(i, 3).toString() : "";
        String col5Value = model.getColumnCount() > 4 && model.getValueAt(i, 4) != null ? model.getValueAt(i, 4).toString() : "";
        String col6Value = model.getColumnCount() > 5 && model.getValueAt(i, 5) != null ? model.getValueAt(i, 5).toString() : "";
        String col7Value = model.getColumnCount() > 6 && model.getValueAt(i, 6) != null ? model.getValueAt(i, 6).toString() : "";

        // Set the values in the SQL statement
        pstmt.setString(1, pat_no);
        pstmt.setString(2, pat_name);
        pstmt.setString(3, col1Value);
        pstmt.setString(4, col2Value);
        pstmt.setString(5, col3Value);
        pstmt.setString(6, col4Value); 
        pstmt.setString(7, col5Value);
        pstmt.setString(8, col6Value);
        pstmt.setString(9, col7Value);
        pstmt.setString(10, verify);
        pstmt.setString(11, date);
        pstmt.setString(12, time);
            
        // Execute the SQL statement
        int rowsAffected = pstmt.executeUpdate();
        
        // Check if the rows were inserted successfully
        if (rowsAffected <= 0) {
            JOptionPane.showMessageDialog(null, "Failed to insert data.");
            break; // exit the loop if insertion fails
        }
    }
    
    // Close the connection
    conn.close();
    
    
    // Display message and clear the table after
JOptionPane.showMessageDialog(null, "Data inserted Succesfully");
model.setRowCount(0);
        pat_name_txt.setText("");
        pat_no_txt.setText("");
    } catch (SQLException ex) {
        ex.printStackTrace();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(parameter_lab.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_txt;
    private javax.swing.JLabel db_connection_status;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField pat_name_txt;
    private javax.swing.JTextField pat_no_txt;
    private javax.swing.JLabel persona_txt;
    private javax.swing.JTable register_report;
    private javax.swing.JTable report_result;
    private javax.swing.JTable test_requested;
    private javax.swing.JLabel time_txt;
    private javax.swing.JComboBox<String> verified_by;
    // End of variables declaration//GEN-END:variables
}
