/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hmis;

/**
 *
 * @author user
 */
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.HeadlessException;
import java.awt.Insets;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
//import javax.swing.text.Document;
import net.proteanit.sql.DbUtils;


public class Nursing extends javax.swing.JFrame {

    /**
     * Creates new form Nursing
     */
    public void setPersonaText(String username) {
        persona_txt.setText(username);
    }
    public Nursing() {
        initComponents();
         showData();
        currentDate();
        
        this.setLocationRelativeTo(null);
    }

    public void currentDate() {
    Calendar cal = new GregorianCalendar();
    int month = cal.get(Calendar.MONTH) + 1;
    int year = cal.get(Calendar.YEAR);
    int day = cal.get(Calendar.DAY_OF_MONTH);

    date_txt.setText(day+ "/" + month + "/" + year);

    int second = cal.get(Calendar.SECOND);
    int minute = cal.get(Calendar.MINUTE);
    int hour = cal.get(Calendar.HOUR_OF_DAY);

    time_txt.setText(hour + "." + minute + "." + second);
}

         
         

    /**
     */
    
     public void showData(){
        try{
            Class.forName("org.postgresql.Driver");
            java.sql.Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","postgres","kanyingi254");
            Statement st = conn.createStatement();
            String query = "select * from patient_details";
            ResultSet rs = st.executeQuery(query);
            register_report.setModel(DbUtils.resultSetToTableModel(rs));
            
            rs.close();
           st.close();
           conn.close();
            
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        pat_name_txt = new javax.swing.JTextField();
        pat_no_txt = new javax.swing.JTextField();
        date_txt = new javax.swing.JLabel();
        time_txt = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        register_report = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        weight_txt = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        bmi_txt = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        temp_txt = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        height_txt = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        bp_txt = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        diastolic_txt = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        systolic_txt = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        o2_txt = new javax.swing.JTextPane();
        jPanel12 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        persona_txt = new javax.swing.JLabel();
        db_connection_status = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jButton3.setText("Patient Card");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(jButton3, gridBagConstraints);

        pat_name_txt.setEditable(false);
        pat_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pat_name_txtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(pat_name_txt, gridBagConstraints);

        pat_no_txt.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(pat_no_txt, gridBagConstraints);

        date_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Date"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(date_txt, gridBagConstraints);

        time_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Time"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(time_txt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jPanel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        jPanel3.add(jDateChooser2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        register_report.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient No", "Patient Name", "Urgency", "Age", "Clinic", "Arrival Time", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        register_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_reportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(register_report);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jTabbedPane1.addTab("Occupancy", jPanel1);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new java.awt.GridBagLayout());

        weight_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Weight"));
        jScrollPane4.setViewportView(weight_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jScrollPane4, gridBagConstraints);

        bmi_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("BMI"));
        jScrollPane2.setViewportView(bmi_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jScrollPane2, gridBagConstraints);

        temp_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperature"));
        jScrollPane6.setViewportView(temp_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jScrollPane6, gridBagConstraints);

        height_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Height"));
        jScrollPane7.setViewportView(height_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jScrollPane7, gridBagConstraints);

        bp_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Blood Pressure"));
        jScrollPane8.setViewportView(bp_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jScrollPane8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel4, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        diastolic_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Diastolic Bp"));
        jScrollPane5.setViewportView(diastolic_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel5.add(jScrollPane5, gridBagConstraints);

        systolic_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Systolic Bp"));
        jScrollPane3.setViewportView(systolic_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel5.add(jScrollPane3, gridBagConstraints);

        o2_txt.setBorder(javax.swing.BorderFactory.createTitledBorder("Oxygen Saturation"));
        jScrollPane9.setViewportView(o2_txt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel5.add(jScrollPane9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel5, gridBagConstraints);

        jPanel12.setLayout(new java.awt.GridBagLayout());

        jButton4.setText("Save Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel12.add(jButton4, gridBagConstraints);

        jButton5.setText("Clear Form");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel12.add(jButton5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel12, gridBagConstraints);

        jTabbedPane1.addTab("Triage", jPanel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        jPanel11.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel11.add(persona_txt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel11.add(db_connection_status, gridBagConstraints);

        jLabel2.setText("Login User :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel11.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel11, gridBagConstraints);

        jMenu6.setText("Setup");

        jMenu7.setText("Staff Registry");

        jMenuItem8.setText("Add User");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuItem9.setText("Edit User");
        jMenu7.add(jMenuItem9);

        jMenu6.add(jMenu7);

        jMenu8.setText("Operating Parameters");

        jMenuItem10.setText("Pharmacy");
        jMenu8.add(jMenuItem10);

        jMenu9.setText("Laboratory");
        jMenu8.add(jMenu9);

        jMenu6.add(jMenu8);

        jMenu10.setText("Exit");
        jMenu6.add(jMenu10);

        jMenuBar1.add(jMenu6);

        jMenu1.setText("Registration");

        jMenuItem2.setText("Out Patient Registration");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Nursing");

        jMenuItem1.setText("Nursing Center");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Clinical");

        jMenuItem3.setText("Clerking");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Eye");
        jMenu3.add(jMenuItem4);

        jMenuItem6.setText("Dental");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laboratory");

        jMenuItem7.setText("Laboratory LIMS");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu11.setText("Billing");

        jMenuItem11.setText("Cash Sale POS");
        jMenu11.add(jMenuItem11);

        jMenuItem12.setText("Dispense Drugs");
        jMenu11.add(jMenuItem12);

        jMenuBar1.add(jMenu11);

        jMenu5.setText("Reports");

        jMenuItem5.setText("Patient Card");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Clerking rgf = new Clerking();
        rgf.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Clerking().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        dispose();
        new lab().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
  String path = "";
JFileChooser j = new JFileChooser();
j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
int x = j.showOpenDialog(this);

if (x == JFileChooser.APPROVE_OPTION) {
    path = j.getSelectedFile().getPath();
}

int rowIndex = register_report.getSelectedRow();

if (rowIndex != -1) {
    String Number = register_report.getValueAt(rowIndex, 0).toString();
    String Name = register_report.getValueAt(rowIndex, 1).toString();
    String Urgency = register_report.getValueAt(rowIndex, 2).toString();
    String Age = register_report.getValueAt(rowIndex, 3).toString();
    String Clinic = register_report.getValueAt(rowIndex, 4).toString();
    String Time = register_report.getValueAt(rowIndex, 5).toString();
    String Date = register_report.getValueAt(rowIndex, 6).toString();

    Document doc = new Document();

    try {
        // Save the PDF file with the patient number as the file name
        PdfWriter.getInstance(doc, new FileOutputStream(path + File.separator + Number + ".pdf"));

        // Add header with logo and text
        Paragraph header = new Paragraph();
        // Add logo
        Image logo = Image.getInstance("src\\main\\java\\com\\mycompany\\icons\\logo.png");
        logo.scaleAbsolute(100f, 100f);
        logo.setAlignment(Element.ALIGN_CENTER);
        header.add(logo);

        // Add header text
        Paragraph headerText = new Paragraph();
        headerText.add(new Phrase("BUNGOMA WEMA CENTER\n Fashion Place Plaza 2nd Floor, Hospital Road\n Opposite Shariffs Centre Next to County Comfort Hotel\n P.o Box 2270-50200 Bungoma \n Tel: 0726982221 \n Email: wemacentre@gmail.com \n"));
        headerText.setAlignment(Element.ALIGN_CENTER);
        header.add(headerText);

        // Center the header
        header.setAlignment(Element.ALIGN_CENTER);

        // Add header to the document
        doc.open();
        doc.add(header);
        doc.add(new Paragraph("\n")); // Add a blank paragraph



        // Add patient data table
        PdfPTable report = new PdfPTable(new float[] { 1, 2 }); // 2 columns: labels on left, data on right
        report.setWidthPercentage(100f);

        report.addCell("Patient Number");
        report.addCell(Number);
        report.addCell("Patient Name");
        report.addCell(Name);
        report.addCell("Gender");
        report.addCell(Urgency);
        report.addCell("Age");
        report.addCell(Age);
        report.addCell("ID");
        report.addCell(Clinic);
        report.addCell("Residence");
        report.addCell(Time);
        report.addCell("Clinic");
        report.addCell(Date);

        doc.add(report);
        
        // Add a row with the text "VITAL SIGNS"


PdfPTable vitalSignsRow = new PdfPTable(1);
Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
Phrase vitalSignsPhrase = new Phrase("VITAL SIGNS", boldFont);
vitalSignsRow.addCell(vitalSignsPhrase);
vitalSignsRow.setWidthPercentage(100f);
doc.add(vitalSignsRow);



      
        
        

// Add vital signs data table
PdfPTable vitalSignsTable = new PdfPTable(new float[] { 1, 1, 5 }); // 3 columns: date, time, vital signs
vitalSignsTable.setWidthPercentage(100f);

// Retrieve vital signs data for the selected patient number
String patNumber = pat_no_txt.getText();
String query = "SELECT  height, weight, bmi, systolic, diastolic, temperature, pressure, oxygen_saturation, date, time FROM vitals  WHERE pat_no = ? order by date ASC, time DESC " ;
try {
    Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","postgres","kanyingi254");
    PreparedStatement pst = conn.prepareStatement(query);
    pst.setString(1, patNumber);
    ResultSet rs = pst.executeQuery();

    // Add the vital signs data to the table
    while (rs.next()) {
        String height = rs.getString("height");
        String weight = rs.getString("weight");
        String bmi = rs.getString("bmi");
        String systolic = rs.getString("systolic");
        String diastolic = rs.getString("diastolic");
        String temperature = rs.getString("temperature");
        String pressure = rs.getString("pressure");
        String oxygenSat = rs.getString("oxygen_saturation");
        String date = rs.getString("date");
        String time = rs.getString("time");

        String vitalSigns = "Height: " + height + ", Weight: " + weight + ", BMI: " + bmi + ", Systolic: " + systolic + ", Diastolic: " + diastolic + ", Temperature: " + temperature + ", Pressure: " + pressure + ", Oxygen Saturation: " + oxygenSat;

        vitalSignsTable.addCell(date);
        vitalSignsTable.addCell(time);
        vitalSignsTable.addCell(vitalSigns);
    }

    // Add the vital signs table to the document
    doc.add(vitalSignsTable);
    
    // Add a row with the text "VITAL SIGNS"
PdfPTable doctorsNotesLabel = new PdfPTable(1);
Font bold = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
Phrase phrase = new Phrase("DOCTORS NOTES", bold);
doctorsNotesLabel.addCell(phrase);
doctorsNotesLabel.setWidthPercentage(100f);
doc.add(doctorsNotesLabel);

    
// Add doctors notes data table
PdfPTable doctorsNotesTable = new PdfPTable(new float[] { 1, 1, 4 }); // 3 columns: date, time, note
doctorsNotesTable.setWidthPercentage(100f);

// Retrieve doctors notes data for the selected patient number
String doctorsNotesQuery = "SELECT history, diagnosis, treatment, date, time FROM public.doc_notes WHERE pat_no = ? ORDER BY date ASC, time DESC";
PreparedStatement doctorsNotesPst = conn.prepareStatement(doctorsNotesQuery);
doctorsNotesPst.setString(1, patNumber);
ResultSet doctorsNotesRs = doctorsNotesPst.executeQuery();

// Add the doctors notes data to the table
while (doctorsNotesRs.next()) {
    String history = doctorsNotesRs.getString("history");
    String diagnosis = doctorsNotesRs.getString("diagnosis");
    String treatment = doctorsNotesRs.getString("treatment");
    String date = doctorsNotesRs.getString("date");
    String time = doctorsNotesRs.getString("time");

    String note = "History: " + history + "\nDiagnosis: " + diagnosis + "\nTreatment: " + treatment;
    doctorsNotesTable.addCell(date);
    doctorsNotesTable.addCell(time);
    doctorsNotesTable.addCell(note);
}

// Add the doctors notes table to the document
doc.add(doctorsNotesTable);

    // Add a row with the text "VITAL SIGNS"
PdfPTable investigationslabel = new PdfPTable(1);
//Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
Phrase phraseinv = new Phrase("INVESTIGATION", boldFont);
investigationslabel.addCell(phraseinv);
investigationslabel.setWidthPercentage(100f);
doc.add(investigationslabel);

    
// Add doctors notes data table
PdfPTable investigations = new PdfPTable(new float[] { 1, 1, 4 }); // 3 columns: date, time, note
investigations.setWidthPercentage(100f);

// Retrieve doctors notes data for the selected patient number
String investigationsQuery = "SELECT  test_requested, date, time FROM public.lab_request WHERE patient_no = ? ORDER BY date ASC, time DESC";
PreparedStatement investigationsPst = conn.prepareStatement(investigationsQuery);
investigationsPst.setString(1, patNumber);
ResultSet investigationsRs = investigationsPst.executeQuery();

// Add the doctors notes data to the table
while (investigationsRs.next()) {
    String test = investigationsRs.getString("test_requested");
    String date = investigationsRs.getString("date");
    String time = investigationsRs.getString("time");

    String note = "Investigation: " + test;
    investigations.addCell(date);
    investigations.addCell(time);
    investigations.addCell(note);
}

// Add the doctors notes table to the document
doc.add(investigations);

// Add a row with the text "LABORATORY RESULTS"
PdfPTable labResultsLabel = new PdfPTable(1);
//Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
Phrase phraseLabResults = new Phrase("LABORATORY RESULTS", boldFont);
labResultsLabel.addCell(phraseLabResults);
labResultsLabel.setWidthPercentage(100f);
doc.add(labResultsLabel);

// Add laboratory results data table
PdfPTable labResultsTable = new PdfPTable(new float[] { 1, 1, 1, 1, 1 }); // 5 columns: parameter, result, lower limit, upper limit, status
labResultsTable.setWidthPercentage(100f);



// Retrieve laboratory results data for the selected patient number
String labResultsQuery = "SELECT test, parameter, result, lower, upper, unit, verified, date, time FROM public.lab_results WHERE patient_no = ? ORDER BY date ASC, time DESC";
PreparedStatement labResultsPst = conn.prepareStatement(labResultsQuery);
labResultsPst.setString(1, patNumber);
ResultSet labResultsRs = labResultsPst.executeQuery();

// Initialize variables to track the current test
String currentTest = "";
boolean isFirstRow = true;

// Declare the verified variable
String verified = "";

// Add the laboratory results data to the table
while (labResultsRs.next()) {
    String test = labResultsRs.getString("test");
    String parameter = labResultsRs.getString("parameter");
    String labResult = labResultsRs.getString("result");
    String lower = labResultsRs.getString("lower");
    String upper = labResultsRs.getString("upper");
    String unit = labResultsRs.getString("unit");
    String date = labResultsRs.getString("date");
    String time = labResultsRs.getString("time");

    // If the test changes, add a new row with the test name in bold
    if (!test.equals(currentTest)) {
        if (!isFirstRow) {
            labResultsTable.completeRow(); // Complete the previous row
        }

        // Add a row with the test name
        PdfPCell testCell = new PdfPCell();
        testCell.setColspan(5);
        Phrase testPhrase = new Phrase("PROCEDURE: " + test, boldFont);
        testCell.addElement(testPhrase);
        labResultsTable.addCell(testCell);
        
        // Add headers for the columns
        labResultsTable.addCell(new PdfPCell(new Phrase("Parameter", boldFont)));
        labResultsTable.addCell(new PdfPCell(new Phrase("Result", boldFont)));
        labResultsTable.addCell(new PdfPCell(new Phrase("Lower Limit", boldFont)));
        labResultsTable.addCell(new PdfPCell(new Phrase("Upper Limit", boldFont)));
        labResultsTable.addCell(new PdfPCell(new Phrase("Status", boldFont)));

        currentTest = test;
        isFirstRow = false;
    }

    // Merge the unit with the result and add it to the table
    String resultWithUnit = labResult + " " + unit;
    labResultsTable.addCell(parameter);
    labResultsTable.addCell(resultWithUnit);
    labResultsTable.addCell(lower);
    labResultsTable.addCell(upper);

    // Check if the result is within the limits
    boolean isWithinLimits = (Double.parseDouble(labResult) >= Double.parseDouble(lower) && Double.parseDouble(labResult) <= Double.parseDouble(upper));

    // Set the status cell color based on the result's position relative to the limits
    PdfPCell statusCell = new PdfPCell();
    statusCell.setBackgroundColor(isWithinLimits ? BaseColor.GREEN : BaseColor.RED);
    labResultsTable.addCell(statusCell);
    
    // Retrieve the "verified" value
    verified = labResultsRs.getString("verified");
}

// Complete the last row if there are any remaining cells
if (!isFirstRow) {
    labResultsTable.completeRow();
}

// Add the laboratory results table to the document
doc.add(labResultsTable);


// Add a row with the text "Results Verified By"
PdfPTable verifiedByRow = new PdfPTable(1);
Phrase verifiedByPhrase = new Phrase();
Chunk verifiedByChunk = new Chunk("Results Verified By: ", boldFont);
verifiedByChunk.append(verified);
verifiedByPhrase.add(verifiedByChunk);
verifiedByRow.addCell(verifiedByPhrase);
verifiedByRow.setWidthPercentage(100f);
doc.add(verifiedByRow);


    // Add a row with the text "VITAL SIGNS"
PdfPTable drugslabel = new PdfPTable(1);
//Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
Phrase drugsinv = new Phrase("DRUGS REQUESTED", boldFont);
drugslabel.addCell(drugsinv);
drugslabel.setWidthPercentage(100f);
doc.add(drugslabel);

    
// Add doctors notes data table
PdfPTable drugs = new PdfPTable(new float[] { 1, 1, 4 }); // 3 columns: date, time, note
drugs.setWidthPercentage(100f); // Set the table width to 100%

// Retrieve doctors notes data for the selected patient number
String drugsQuery = "SELECT drug,  quantity_requested, strength, date, time, notes FROM public.drugs_requested WHERE pat_no = ? ORDER BY date ASC, time DESC";
PreparedStatement drugsPst = conn.prepareStatement(drugsQuery);
drugsPst.setString(1, patNumber);
ResultSet drugsRs = drugsPst.executeQuery();

// Add the doctors notes data to the table
while (drugsRs.next()) {
    String test = drugsRs.getString("drug");
    String date = drugsRs.getString("date");
    String time = drugsRs.getString("time");

    String note = "Drug: " + test;
    drugs.addCell(date);
    drugs.addCell(time);
    drugs.addCell(note);
}

// Set the number of columns to span for the note column
int noteColumnSpan = 3;
drugs.getDefaultCell().setColspan(noteColumnSpan);

// Add the doctors notes table to the document
doc.add(drugs);







// Close the database connection
conn.close();



    // Close the document
    doc.close();
    
} catch (SQLException ex) {
    Logger.getLogger(Clerking.class.getName()).log(Level.SEVERE, null, ex);
}

 



        
        
        
        JOptionPane.showMessageDialog(null, "File Downloaded Successfully", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);

    } catch (FileNotFoundException ex) {
        Logger.getLogger(Clerking.class.getName()).log(Level.SEVERE, null, ex);
    } catch (DocumentException ex) {
        Logger.getLogger(Clerking.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(Clerking.class.getName()).log(Level.SEVERE, null, ex);
    }

    doc.close();
}




   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pat_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_name_txtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("org.postgresql.Driver");
            java.sql.Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres","postgres","kanyingi254");
            String pat_no = pat_no_txt.getText();
            String name = pat_name_txt.getText();
            String height = height_txt.getText();

            String weight = weight_txt.getText();
            String bmi = bmi_txt.getText();
            String systolic = systolic_txt.getText();
            String diastolic = diastolic_txt.getText();
            String temp = temp_txt.getText();
            String pressure = bp_txt.getText();
            String oxygen = o2_txt.getText();
            String date = date_txt.getText();
            String time = time_txt.getText();

            String query = "INSERT INTO public.vitals (pat_no, pat_name, height, weight, bmi, systolic, diastolic, temperature, pressure, oxygen_saturation, date, time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?);";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, pat_no);
            pst.setString(2, name);
            pst.setString(3, height);

            pst.setString(4, weight);
            pst.setString(5, bmi);
            pst.setString(6, systolic);
            pst.setString(7, diastolic);
            pst.setString(8, temp);
            pst.setString(9, pressure);
            pst.setString(10, oxygen);
            pst.setString(11, date);
            pst.setString(12, time);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Inserted successfully");
            //Homepa receptionist = new Homepage();
            register_report.show();
        }catch(HeadlessException | ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void register_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_reportMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel) register_report.getModel();
        int i = register_report.getSelectedRow();
        try{
            pat_no_txt.setText(model.getValueAt(i, 0).toString());
            pat_name_txt.setText(model.getValueAt(i, 1).toString());
        }catch(Exception e){
        }
    }//GEN-LAST:event_register_reportMouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        dispose();
        new register_user().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nursing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nursing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nursing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nursing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nursing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane bmi_txt;
    private javax.swing.JTextPane bp_txt;
    private javax.swing.JLabel date_txt;
    private javax.swing.JLabel db_connection_status;
    private javax.swing.JTextPane diastolic_txt;
    private javax.swing.JTextPane height_txt;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane o2_txt;
    private javax.swing.JTextField pat_name_txt;
    private javax.swing.JTextField pat_no_txt;
    private javax.swing.JLabel persona_txt;
    private javax.swing.JTable register_report;
    private javax.swing.JTextPane systolic_txt;
    private javax.swing.JTextPane temp_txt;
    private javax.swing.JLabel time_txt;
    private javax.swing.JTextPane weight_txt;
    // End of variables declaration//GEN-END:variables

    
}
